# Two services: backend API on 5000, frontend (nginx) on 80
services:
  mern-task-server:
    build: ./server
    container_name: mern-task-server
    restart: always
    env_file:
      - ./server/.env        
    ports:
      - "5000:5000"

  mern-task-client:
    build:
      context: ./client
      # args:
      #   VITE_API_URL: http://3.26.242.54:5000/api
    container_name: mern-task-client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - mern-task-server